FROM ubuntu:24.04 AS vllm-base

WORKDIR /workspace/

ARG PYTHON_VERSION=3.12
ARG PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/test/xpu"
ARG INTEL_OMIX_VERSION=0.4
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    ffmpeg \
    git \
    ccache \
    gnupg \
    libsndfile1 \
    libsm6 \
    libxext6 \
    libgl1 \
    lsb-release \
    numactl \
    wget \
    vim \
    python3.12 \
    python3.12-dev && \
    rm -rf /var/lib/apt/lists/*

RUN \
    curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | \
        gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu noble/intel-omix/${INTEL_OMIX_VERSION} unified" \
        > /etc/apt/sources.list.d/intel-gpu-noble.list && \
    apt-get update -o APT::Update::Error-Mode=any && \
    apt-get install -y --no-install-recommends intel-omix-dev && \
    /opt/intel/oneapi/compiler/latest/bin/icpx --version && \
    rm -rf /var/lib/apt/lists/*

ENV ONEAPI_ROOT="/opt/intel/oneapi"
ENV CMPLR_ROOT="${ONEAPI_ROOT}/compiler/latest"
ENV MKLROOT="${ONEAPI_ROOT}/mkl/latest"
ENV PATH="${ONEAPI_ROOT}/compiler/latest/bin:${PATH}"

ENV PATH="/root/.local/bin:$PATH"
ENV VIRTUAL_ENV="/opt/venv"
ENV UV_PYTHON_INSTALL_DIR=/opt/uv/python
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN uv venv --python ${PYTHON_VERSION} --seed ${VIRTUAL_ENV}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENV UV_HTTP_TIMEOUT=500

ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_STRATEGY="unsafe-best-match"
ENV UV_LINK_MODE="copy"
