function(fmha_forward_configure)
set(FMHA_FORWARD_KERNEL_SRCS)  # output
set(L_TYPES "fp16" "bf16")
set(L_BOOLS "false" "true")
set(BOOL_FLAG_false "f")
set(BOOL_FLAG_true "t")
set(policy_list "chunk_policy_head64" "chunk_policy_head96" "chunk_policy_head128" "chunk_policy_head192" "chunk_policy_head256")

set(IMPL_KV_T "fp16")

foreach(IMPL_POLICY ${policy_list})
# foreach(IMPL_T ${L_TYPES})
foreach(IMPL_KISPAGED ${L_BOOLS})
foreach(IMPL_KISCAUSAL ${L_BOOLS})
foreach(IMPL_KISLOCAL ${L_BOOLS})
foreach(IMPL_KISSINK ${L_BOOLS})
    set(FILE_SUFFIX "_${IMPL_POLICY}_${IMPL_T}_${IMPL_KV_T}_")
    set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISPAGED}}")
    set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISCAUSAL}}")
    set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISSINK}}")
    set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISLOCAL}}")
    configure_file(chunk_prefill_kernel.cpp.in "chunk_prefill_kernel_${FILE_SUFFIX}.cpp")
    list(APPEND FMHA_FORWARD_KERNEL_SRCS "${CMAKE_CURRENT_BINARY_DIR}/chunk_prefill_kernel_${FILE_SUFFIX}.cpp")
endforeach()
endforeach()
endforeach()
endforeach()
endforeach()

list(REMOVE_DUPLICATES FMHA_FORWARD_KERNEL_SRCS)
list(LENGTH FMHA_FORWARD_KERNEL_SRCS FMHA_FORWARD_KERNEL_SRCS_LENGTH)
message(STATUS "Generated chunk prefill kernel sources: ${FMHA_FORWARD_KERNEL_SRCS_LENGTH}")
set(FMHA_FORWARD_KERNEL_SRCS ${FMHA_FORWARD_KERNEL_SRCS} PARENT_SCOPE)
set(FMHA_FORWARD_KERNEL_SRCS_LENGTH ${FMHA_FORWARD_KERNEL_SRCS_LENGTH} PARENT_SCOPE)
endfunction()