function(fmha_forward_configure FILENAME_SUFFIX)
  set(GEN_KERNEL_SRCS)
  set(BOOL_FLAG_false "f")
  set(BOOL_FLAG_true "t")
  set(policy_list "chunk_policy_head128")
  set(IMPL_KV_T "fp16")
  foreach(IMPL_POLICY ${policy_list})
    foreach(IMPL_KISPAGED "false")
      foreach(IMPL_KISCAUSAL "true")
        foreach(IMPL_KISLOCAL "false")
          foreach(IMPL_KISSINK "false")
            foreach(IMPL_KISLSE "false" "true")
              set(FILE_SUFFIX "${IMPL_POLICY}_")
              set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISPAGED}}")
              set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISCAUSAL}}")
              set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISSINK}}")
              set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISLOCAL}}")
              set(FILE_SUFFIX "${FILE_SUFFIX}${BOOL_FLAG_${IMPL_KISLSE}}")
              configure_file(${FILENAME_SUFFIX}.cpp.in "${FILENAME_SUFFIX}_${FILE_SUFFIX}.cpp")
              list(APPEND GEN_KERNEL_SRCS "${CMAKE_CURRENT_BINARY_DIR}/${FILENAME_SUFFIX}_${FILE_SUFFIX}.cpp")
            endforeach()
          endforeach()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES GEN_KERNEL_SRCS)
  list(LENGTH GEN_KERNEL_SRCS GEN_KERNEL_SRCS_LENGTH)
  message(STATUS "Generated ${FILENAME_SUFFIX} kernel sources: ${GEN_KERNEL_SRCS_LENGTH}")
  set(GEN_KERNEL_SRCS ${GEN_KERNEL_SRCS} PARENT_SCOPE)
  set(ATTN_KERNEL_SRCS_GEN ${GEN_KERNEL_SRCS} PARENT_SCOPE)
endfunction()
