#pragma once

#include "chunk_prefill.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new head size policy, simply add it to this X-Macro list:
// X(policy_name)
#define CHUNK_POLICY_LIST(X)  \
  X(chunk_policy_head64)      \
  X(chunk_policy_head96)      \
  X(chunk_policy_head128)     \
  X(chunk_policy_head192)     \
  X(chunk_policy_head256)     \
  X(chunk_policy_head512)     \
  X(chunk_policy_head64_b16)  \
  X(chunk_policy_head96_b16)  \
  X(chunk_policy_head128_b16) \
  X(chunk_policy_head192_b16) \
  X(chunk_policy_head256_b16) \
  X(chunk_policy_head512_b16)

// =============================================================================
// Automatic extern template declarations for all policies
// =============================================================================
// Prevent implicit instantiation of policy_dispatch_impl in translation units
// that include chunk_prefill.hpp. Each policy is explicitly instantiated in its
// own .cpp file generated by CMake.

// Helper macro to declare a single extern template instantiation
#define DECLARE_POLICY_DISPATCH_EXTERN(POLICY)       \
  extern template void policy_dispatch_impl<POLICY>( \
      sycl::queue & queue,                           \
      CutlassQKType & cuQKType,                      \
      const chunk_prefill_args_t& args);

CHUNK_POLICY_LIST(DECLARE_POLICY_DISPATCH_EXTERN)

#undef DECLARE_POLICY_DISPATCH_EXTERN
