#pragma once

#include "chunk_prefill.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new head size policy, simply add it to this X-Macro list:
// X(policy_name)
#define CHUNK_POLICY_LIST(X)  \
  X(chunk_policy_head64)      \
  X(chunk_policy_head96)      \
  X(chunk_policy_head128)     \
  X(chunk_policy_head192)     \
  X(chunk_policy_head256)     \
  X(chunk_policy_head512)     \
  X(chunk_policy_head64_b16)  \
  X(chunk_policy_head96_b16)  \
  X(chunk_policy_head128_b16) \
  X(chunk_policy_head192_b16) \
  X(chunk_policy_head256_b16) \
  X(chunk_policy_head512_b16)

// =============================================================================
// Automatic extern template declarations for all policy combinations
// =============================================================================
// Prevent implicit instantiation of policy_dispatch_impl in translation units
// that include chunk_prefill.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

// Helper macro to declare a single extern template instantiation
#define DECLARE_POLICY_DISPATCH_EXTERN(                          \
    POLICY, PAGED, CAUSAL, LOCAL, SINK, LSE)                     \
  extern template void                                           \
  policy_dispatch_impl<POLICY, PAGED, CAUSAL, LOCAL, SINK, LSE>( \
      sycl::queue & queue,                                       \
      CutlassQKType & cuQKType,                                  \
      const chunk_prefill_args_t& args);

// Generate bool combinations for a given policy.
// softmax_lse (LSE) is only supported on the (Paged=false, Local=false,
// Sink=false) specialization; for all other combos LSE is forced false.
// Total per policy: 14 LSE=false combos + 2 LSE=T/F combos
// (P=F,L=F,S=F × Causal=T/F) × 2 = 4 -> 14 + 4 = 18 instantiations.

// LSE axis: both true and false (only valid when P=F,L=F,S=F)
#define DECLARE_FOR_LSE_BOTH(POLICY, PAGED, CAUSAL, LOCAL, SINK)            \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, false) \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, true)

// LSE axis: only false (all other P/L/S combos)
#define DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, SINK) \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, false)

// Sink axis (innermost for the unconstrained P/L/S tree -> LSE=false only)
#define DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, LOCAL) \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, false)     \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, true)

#define DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, CAUSAL) \
  DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, false) \
  DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, true)

#define DECLARE_FOR_CAUSAL_FALSEONLY(POLICY, PAGED) \
  DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, false) \
  DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, true)

// P=F,L=F,S=F branch (LSE=T/F allowed): Causal axis only.
#define DECLARE_LSE_ALLOWED_BRANCH(POLICY)                 \
  DECLARE_FOR_LSE_BOTH(POLICY, false, false, false, false) \
  DECLARE_FOR_LSE_BOTH(POLICY, false, true, false, false)

// P=F but (L=true OR S=true): LSE=false only. Causal × Local × Sink (minus
// the all-false case already covered above).
#define DECLARE_PAGED_FALSE_OTHER(POLICY)                  \
  /* Causal=F, Local=F, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, false, false, true) \
  /* Causal=F, Local=T, Sink=F */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, false, true, false) \
  /* Causal=F, Local=T, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, false, true, true)  \
  /* Causal=T, Local=F, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, true, false, true)  \
  /* Causal=T, Local=T, Sink=F */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, true, true, false)  \
  /* Causal=T, Local=T, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, false, true, true, true)

// P=T branch: LSE=false only across all Causal × Local × Sink.
#define DECLARE_ALL_BOOL_COMBINATIONS(POLICY) \
  DECLARE_LSE_ALLOWED_BRANCH(POLICY)          \
  DECLARE_PAGED_FALSE_OTHER(POLICY)           \
  DECLARE_FOR_CAUSAL_FALSEONLY(POLICY, true)

// Apply the bool combination generator to all policies
CHUNK_POLICY_LIST(DECLARE_ALL_BOOL_COMBINATIONS)

// Cleanup macros
#undef DECLARE_ALL_BOOL_COMBINATIONS
#undef DECLARE_LSE_ALLOWED_BRANCH
#undef DECLARE_PAGED_FALSE_OTHER
#undef DECLARE_FOR_CAUSAL_FALSEONLY
#undef DECLARE_FOR_LOCAL_FALSEONLY
#undef DECLARE_FOR_SINK_FALSEONLY
#undef DECLARE_FOR_LSE_FALSE
#undef DECLARE_FOR_LSE_BOTH
#undef DECLARE_POLICY_DISPATCH_EXTERN
