#pragma once

#include "chunk_prefill.hpp"

namespace vllm::xpu::xe2 {
// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new head size policy, simply add it to this X-Macro list:
// X(policy_name)
#define CHUNK_POLICY_LIST(X)  \
  X(chunk_policy_head64)      \
  X(chunk_policy_head96)      \
  X(chunk_policy_head128)     \
  X(chunk_policy_head192)     \
  X(chunk_policy_head256)     \
  X(chunk_policy_head512)     \
  X(chunk_policy_head64_b16)  \
  X(chunk_policy_head96_b16)  \
  X(chunk_policy_head128_b16) \
  X(chunk_policy_head192_b16) \
  X(chunk_policy_head256_b16) \
  X(chunk_policy_head512_b16)

// =============================================================================
// Automatic extern template declarations for all policy combinations
// =============================================================================
// Prevent implicit instantiation of policy_dispatch_impl in translation units
// that include chunk_prefill.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

// Helper macro to declare a single extern template instantiation
#define DECLARE_POLICY_DISPATCH_EXTERN(                          \
    POLICY, PAGED, CAUSAL, LOCAL, SINK, LSE)                     \
  extern template void                                           \
  policy_dispatch_impl<POLICY, PAGED, CAUSAL, LOCAL, SINK, LSE>( \
      sycl::queue & queue,                                       \
      CutlassQKType & cuQKType,                                  \
      const chunk_prefill_args_t& args);

// Generate bool combinations for a given policy.
// Paged and non-paged kernels support LSE=true for Local=false,Sink=false.
// Total per policy: 10 paged + 10 non-paged = 20 instantiations.

// LSE axis: both true and false.
#define DECLARE_FOR_LSE_BOTH(POLICY, PAGED, CAUSAL, LOCAL, SINK)            \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, false) \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, true)

// LSE axis: only false (all other P/L/S combos)
#define DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, SINK) \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK, false)

// Sink axis for LSE=false-only branches.
#define DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, LOCAL) \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, false)     \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, CAUSAL, LOCAL, true)

#define DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, CAUSAL) \
  DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, false) \
  DECLARE_FOR_SINK_FALSEONLY(POLICY, PAGED, CAUSAL, true)

#define DECLARE_FOR_CAUSAL_FALSEONLY(POLICY, PAGED) \
  DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, false) \
  DECLARE_FOR_LOCAL_FALSEONLY(POLICY, PAGED, true)

// Local=F,Sink=F branch (LSE=T/F allowed): Causal axis only.
#define DECLARE_LSE_ALLOWED_BRANCH(POLICY, PAGED)          \
  DECLARE_FOR_LSE_BOTH(POLICY, PAGED, false, false, false) \
  DECLARE_FOR_LSE_BOTH(POLICY, PAGED, true, false, false)

// Local=true or Sink=true: LSE=false only. Causal × Local × Sink (minus
// the all-false case already covered above).
#define DECLARE_LSE_DISABLED_BRANCH(POLICY, PAGED)         \
  /* Causal=F, Local=F, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, false, false, true) \
  /* Causal=F, Local=T, Sink=F */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, false, true, false) \
  /* Causal=F, Local=T, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, false, true, true)  \
  /* Causal=T, Local=F, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, true, false, true)  \
  /* Causal=T, Local=T, Sink=F */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, true, true, false)  \
  /* Causal=T, Local=T, Sink=T */                          \
  DECLARE_FOR_LSE_FALSE(POLICY, PAGED, true, true, true)

#define DECLARE_ALL_BOOL_COMBINATIONS(POLICY) \
  DECLARE_LSE_ALLOWED_BRANCH(POLICY, false)   \
  DECLARE_LSE_DISABLED_BRANCH(POLICY, false)  \
  DECLARE_LSE_ALLOWED_BRANCH(POLICY, true)    \
  DECLARE_LSE_DISABLED_BRANCH(POLICY, true)

// Apply the bool combination generator to all policies
CHUNK_POLICY_LIST(DECLARE_ALL_BOOL_COMBINATIONS)

// Cleanup macros
#undef DECLARE_ALL_BOOL_COMBINATIONS
#undef DECLARE_LSE_ALLOWED_BRANCH
#undef DECLARE_LSE_DISABLED_BRANCH
#undef DECLARE_FOR_CAUSAL_FALSEONLY
#undef DECLARE_FOR_LOCAL_FALSEONLY
#undef DECLARE_FOR_SINK_FALSEONLY
#undef DECLARE_FOR_LSE_FALSE
#undef DECLARE_FOR_LSE_BOTH
#undef DECLARE_POLICY_DISPATCH_EXTERN

}  // namespace vllm::xpu::xe2
