#pragma once

#include "paged_decode.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new decode policy, simply add it to this X-Macro list
#define DECODE_POLICY_LIST(X)              \
  X(decode_policy_qpacked_head<_8, _64>)   \
  X(decode_policy_qpacked_head<_8, _96>)   \
  X(decode_policy_qpacked_head<_8, _128>)  \
  X(decode_policy_qpacked_head<_8, _192>)  \
  X(decode_policy_qpacked_head<_8, _256>)  \
  X(decode_policy_qpacked_head<_16, _64>)  \
  X(decode_policy_qpacked_head<_16, _96>)  \
  X(decode_policy_qpacked_head<_16, _128>) \
  X(decode_policy_qpacked_head<_16, _192>) \
  X(decode_policy_qpacked_head<_16, _256>)

// =============================================================================
// Automatic extern template declarations for all policy combinations
// =============================================================================
// Prevent implicit instantiation of decode_policy_dispatch in translation units
// that include paged_decode.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

// Helper macro to declare a single extern template instantiation
#define DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, SINK)         \
  extern template void decode_policy_dispatch<POLICY, CAUSAL, LOCAL, SINK>( \
      sycl::queue & queue,                                                  \
      CutlassType cuType,                                                   \
      const paged_decode_args_t& args);

// Generate all 8 bool combinations for a given policy using nested macros
// Pattern: Causal, Local, Sink (all permutations of 3 bools = 2^3 = 8)
// This hierarchical approach makes it easy to extend to more bool parameters

// Level 3: Iterate over Sink values (innermost)
#define DECLARE_FOR_SINK(POLICY, CAUSAL, LOCAL)                \
  DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, false) \
  DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, true)

// Level 2: Iterate over Local values
#define DECLARE_FOR_LOCAL(POLICY, CAUSAL) \
  DECLARE_FOR_SINK(POLICY, CAUSAL, false) \
  DECLARE_FOR_SINK(POLICY, CAUSAL, true)

// Level 1: Iterate over Causal values (outermost)
#define DECLARE_ALL_BOOL_COMBINATIONS(POLICY) \
  DECLARE_FOR_LOCAL(POLICY, false)            \
  DECLARE_FOR_LOCAL(POLICY, true)

// Apply the bool combination generator to all policies
DECODE_POLICY_LIST(DECLARE_ALL_BOOL_COMBINATIONS)

// Cleanup macros
#undef DECLARE_ALL_BOOL_COMBINATIONS
#undef DECLARE_FOR_LOCAL
#undef DECLARE_FOR_SINK
#undef DECLARE_DECODE_DISPATCH_EXTERN
