#pragma once

#include "paged_decode.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new decode policy, define aliases to avoid comma issues in macros

// X-Macro list using aliases
#define PAGED_DECODE_POLICY_LIST(X) \
  X(decode_policy_q8_h64_p64)       \
  X(decode_policy_q8_h96_p64)       \
  X(decode_policy_q8_h128_p64)      \
  X(decode_policy_q8_h192_p64)      \
  X(decode_policy_q8_h256_p64)      \
  X(decode_policy_q8_h512_p64)      \
  X(decode_policy_q16_h64_p64)      \
  X(decode_policy_q16_h96_p64)      \
  X(decode_policy_q16_h128_p64)     \
  X(decode_policy_q16_h192_p64)     \
  X(decode_policy_q16_h256_p64)     \
  X(decode_policy_q16_h512_p64)     \
  X(decode_policy_q8_h576_p64)      \
  X(decode_policy_q16_h576_p64)     \
  X(decode_policy_q8_h64_p128)      \
  X(decode_policy_q8_h96_p128)      \
  X(decode_policy_q8_h128_p128)     \
  X(decode_policy_q8_h192_p128)     \
  X(decode_policy_q8_h256_p128)     \
  X(decode_policy_q8_h512_p128)     \
  X(decode_policy_q16_h64_p128)     \
  X(decode_policy_q16_h96_p128)     \
  X(decode_policy_q16_h128_p128)    \
  X(decode_policy_q16_h192_p128)    \
  X(decode_policy_q16_h256_p128)    \
  X(decode_policy_q16_h512_p128)    \
  X(decode_policy_q8_h64_p16)       \
  X(decode_policy_q8_h96_p16)       \
  X(decode_policy_q8_h128_p16)      \
  X(decode_policy_q8_h192_p16)      \
  X(decode_policy_q8_h256_p16)      \
  X(decode_policy_q8_h512_p16)      \
  X(decode_policy_q16_h64_p16)      \
  X(decode_policy_q16_h96_p16)      \
  X(decode_policy_q16_h128_p16)     \
  X(decode_policy_q16_h192_p16)     \
  X(decode_policy_q16_h256_p16)     \
  X(decode_policy_q16_h512_p16)     \
  X(decode_policy_q8_h64_p32)       \
  X(decode_policy_q8_h96_p32)       \
  X(decode_policy_q8_h128_p32)      \
  X(decode_policy_q8_h192_p32)      \
  X(decode_policy_q8_h256_p32)      \
  X(decode_policy_q8_h512_p32)      \
  X(decode_policy_q16_h64_p32)      \
  X(decode_policy_q16_h96_p32)      \
  X(decode_policy_q16_h128_p32)     \
  X(decode_policy_q16_h192_p32)     \
  X(decode_policy_q16_h256_p32)     \
  X(decode_policy_q16_h512_p32)     \
  X(decode_policy_q8_h576_p128)     \
  X(decode_policy_q16_h576_p128)

// =============================================================================
// Q/KV dtype combinations
// =============================================================================
// Mirrors CHUNK_DTYPE_COMBINATIONS in chunk_prefill_extern.hpp. Keep both
// lists, paged_decode_configure.cmake, and the dtype dispatch in
// paged_decode_utils.hpp in lockstep.
#define DECODE_DTYPE_COMBINATIONS(X, ...)           \
  X(__VA_ARGS__, half_t, half_t)                    \
  X(__VA_ARGS__, half_t, float_e4m3_t)              \
  X(__VA_ARGS__, half_t, float_e5m2_t)              \
  X(__VA_ARGS__, bfloat16_t, bfloat16_t)            \
  X(__VA_ARGS__, bfloat16_t, float_e4m3_t)          \
  X(__VA_ARGS__, bfloat16_t, float_e5m2_t)

// =============================================================================
// Automatic extern template declarations for all policy combinations
// =============================================================================
// Prevent implicit instantiation of decode_policy_dispatch_impl in translation
// units that include paged_decode.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

#define DECLARE_DECODE_DISPATCH_EXTERN_ONE(POLICY, CAUSAL, LOCAL, SINK, Q, KV) \
  extern template void                                                          \
  decode_policy_dispatch_impl<POLICY, CAUSAL, LOCAL, SINK, Q, KV>(               \
      sycl::queue & queue, const paged_decode_args_t& args);

#define DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, SINK) \
  DECODE_DTYPE_COMBINATIONS(                                        \
      DECLARE_DECODE_DISPATCH_EXTERN_ONE, POLICY, CAUSAL, LOCAL, SINK)

// Generate all 8 bool combinations for a given policy using nested macros
// Pattern: Causal, Local, Sink (all permutations of 3 bools = 2^3 = 8)
// This hierarchical approach makes it easy to extend to more bool parameters

// Level 3: Iterate over Sink values (innermost)
#define DECLARE_FOR_SINK(POLICY, CAUSAL, LOCAL)                \
  DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, false) \
  DECLARE_DECODE_DISPATCH_EXTERN(POLICY, CAUSAL, LOCAL, true)

// Level 2: Iterate over Local values
#define DECLARE_FOR_LOCAL(POLICY, CAUSAL) \
  DECLARE_FOR_SINK(POLICY, CAUSAL, false) \
  DECLARE_FOR_SINK(POLICY, CAUSAL, true)

// Level 1: Iterate over Causal values (outermost)
#define DECLARE_ALL_BOOL_COMBINATIONS(POLICY) \
  DECLARE_FOR_LOCAL(POLICY, false)            \
  DECLARE_FOR_LOCAL(POLICY, true)

// Apply the bool combination generator to all policies
PAGED_DECODE_POLICY_LIST(DECLARE_ALL_BOOL_COMBINATIONS)

// Cleanup macros
#undef DECLARE_ALL_BOOL_COMBINATIONS
#undef DECLARE_FOR_LOCAL
#undef DECLARE_FOR_SINK
#undef DECLARE_DECODE_DISPATCH_EXTERN
#undef DECLARE_DECODE_DISPATCH_EXTERN_ONE
