#pragma once

#include "paged_decode.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new decode policy, define aliases to avoid comma issues in macros

// X-Macro list using aliases
#define PAGED_DECODE_POLICY_LIST(X) \
  X(decode_policy_q8_h64_p64)       \
  X(decode_policy_q8_h96_p64)       \
  X(decode_policy_q8_h128_p64)      \
  X(decode_policy_q8_h192_p64)      \
  X(decode_policy_q8_h256_p64)      \
  X(decode_policy_q8_h512_p64)      \
  X(decode_policy_q16_h64_p64)      \
  X(decode_policy_q16_h96_p64)      \
  X(decode_policy_q16_h128_p64)     \
  X(decode_policy_q16_h192_p64)     \
  X(decode_policy_q16_h256_p64)     \
  X(decode_policy_q16_h512_p64)     \
  X(decode_policy_q8_h576_p64)      \
  X(decode_policy_q16_h576_p64)     \
  X(decode_policy_q8_h64_p128)      \
  X(decode_policy_q8_h96_p128)      \
  X(decode_policy_q8_h128_p128)     \
  X(decode_policy_q8_h192_p128)     \
  X(decode_policy_q8_h256_p128)     \
  X(decode_policy_q8_h512_p128)     \
  X(decode_policy_q16_h64_p128)     \
  X(decode_policy_q16_h96_p128)     \
  X(decode_policy_q16_h128_p128)    \
  X(decode_policy_q16_h192_p128)    \
  X(decode_policy_q16_h256_p128)    \
  X(decode_policy_q16_h512_p128)    \
  X(decode_policy_q8_h64_p16)       \
  X(decode_policy_q8_h96_p16)       \
  X(decode_policy_q8_h128_p16)      \
  X(decode_policy_q8_h192_p16)      \
  X(decode_policy_q8_h256_p16)      \
  X(decode_policy_q8_h512_p16)      \
  X(decode_policy_q16_h64_p16)      \
  X(decode_policy_q16_h96_p16)      \
  X(decode_policy_q16_h128_p16)     \
  X(decode_policy_q16_h192_p16)     \
  X(decode_policy_q16_h256_p16)     \
  X(decode_policy_q16_h512_p16)     \
  X(decode_policy_q8_h64_p32)       \
  X(decode_policy_q8_h96_p32)       \
  X(decode_policy_q8_h128_p32)      \
  X(decode_policy_q8_h192_p32)      \
  X(decode_policy_q8_h256_p32)      \
  X(decode_policy_q8_h512_p32)      \
  X(decode_policy_q16_h64_p32)      \
  X(decode_policy_q16_h96_p32)      \
  X(decode_policy_q16_h128_p32)     \
  X(decode_policy_q16_h192_p32)     \
  X(decode_policy_q16_h256_p32)     \
  X(decode_policy_q16_h512_p32)     \
  X(decode_policy_q8_h576_p128)     \
  X(decode_policy_q16_h576_p128)

// =============================================================================
// Automatic extern template declarations for all enabled policies
// =============================================================================
// Prevent implicit instantiation of decode_policy_dispatch_impl in translation
// units that include paged_decode.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

#define DECLARE_DECODE_DISPATCH_EXTERN(POLICY)              \
  extern template void decode_policy_dispatch_impl<POLICY>( \
      sycl::queue & queue,                                  \
      CutlassQKType & cuQKType,                             \
      const paged_decode_args_t& args);

PAGED_DECODE_POLICY_LIST(DECLARE_DECODE_DISPATCH_EXTERN)

#undef DECLARE_DECODE_DISPATCH_EXTERN
